import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { useGSAP } from "@gsap/react";
import gsap from "gsap";
import { Toaster } from "react-hot-toast";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  gsap.registerPlugin(useGSAP);



  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} dark:text-white dark:bg-dark h-dvh`}>
        {children}
        <Toaster
          position="bottom-right"
        />
      </body>
    </html>
  );
}
